### ISSUE TITLE
Errors submitting manifest

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic#1119]
**Describe the bug**
I'm getting the two errors below submitting a manifest `schematic model -c ../schematic/config.yml submit -mp synapse_storage_manifest.csv -d syn50896918 -vc Genes`
[schema](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.jsonld)

**Expected behavior**
The manifest should submit. 
- row 3 the attribute hgnc_id is `A2MP1`, I'm not sure how that is not a string
- `syn50896918` is definitely in this [asset view](https://www.synapse.org/#!Synapse:syn50864462/tables/)

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

```
schematic model -c ../schematic/config.yml submit -mp synapse_storage_manifest.csv -d syn50896918 -vc Genes
Starting schematic...
The (model > input > location) argument with value '../iAtlasSchema/iatlas_schema.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   55.7kB/55.7kB (675.8kB/s) SYNAPSE_TABLE_QUERY_121331300.csv Done...
    JSON schema successfully generated from schema.org schema!
JSON schema file log stored as ../iAtlasSchema/iatlas_schema.Genes.schema.json
FileDataContext loading zep config
GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
GxConfig.parse_yaml() returning empty `xdatasources`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
EphemeralDataContext has not implemented `_load_zep_config()` returning empty `GxConfig`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
warning:   return concat(self.root_render_func(self.new_context(vars)))
	10 expectation(s) included in expectation_suite.
Calculating Metrics: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 66/66 [00:00<00:00, 639.39it/s]
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
warning:   return concat(self.root_render_func(self.new_context(vars)))
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/jinja2/environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
warning:   return concat(self.root_render_func(self.new_context(vars)))
error: On row 3 the attribute hgnc_id does not contain the proper value type str.
error: 'syn50896918' could not be found in the asset view (or file view for Synapse user)
```

**Comment by andrewelamb** [comment]
manifest:
[synapse_storage_manifest.csv](https://github.com/Sage-Bionetworks/schematic/files/10667444/synapse_storage_manifest.csv)

**Comment by milen-sage** [comment]
Related to #1097

**Comment by andrewelamb** [comment]
@milen-sage, @GiaJordan I'm still seeing this error with the latest version of schematic

**Comment by andrewelamb** [comment]
```
(schematicpy-gKAjXOOq-py3.9) (base) alamb@ALamb:~/repos/iatlasManifests$ schematic model -c ../schematic/config.yml submit -mp synapse_storage_manifest.csv -d syn51080454 -vc Datasets
Starting schematic...
The (model > input > location) argument with value '../iAtlasSchema/iatlas_schema.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (657.1kB/s) SYNAPSE_TABLE_QUERY_121729655.csv Done...
    JSON schema successfully generated from schema.org schema!
JSON schema file log stored as ../iAtlasSchema/iatlas_schema.Datasets.schema.json
Could not find local context root directory
Created temporary directory '/tmp/tmp5r81a0gt' for ephemeral docs site
EphemeralDataContext has not implemented `_load_zep_config()` returning empty `GxConfig`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
Could not find local context root directory
EphemeralDataContext has not implemented `_load_zep_config()` returning empty `GxConfig`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2705: DeprecationWarning: create_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use add_expectation_suite or add_or_update_expectation_suite instead.
  warnings.warn(

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2705: DeprecationWarning: create_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use add_expectation_suite or add_or_update_expectation_suite instead.
warning:   warnings.warn(
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:416: DeprecationWarning: save_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use update_expectation_suite or add_or_update_expectation_suite instead.
  warnings.warn(

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:416: DeprecationWarning: save_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use update_expectation_suite or add_or_update_expectation_suite instead.
warning:   warnings.warn(
	4 expectation(s) included in expectation_suite.
Calculating Metrics: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 681.57it/s]
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (67.0MB/s) SYNAPSE_TABLE_QUERY_121729657.csv Done...
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (628.6kB/s) SYNAPSE_TABLE_QUERY_121729659.csv Done...
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (644.8kB/s) SYNAPSE_TABLE_QUERY_121729661.csv Done...
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (351.1kB/s) SYNAPSE_TABLE_QUERY_121729664.csv Done...
 [####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   56.3kB/56.3kB (654.5kB/s) SYNAPSE_TABLE_QUERY_121729667.csv Done...
    Traceback (most recent call last):
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/bin/schematic", line 6, in <module>
    sys.exit(main())
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/alamb/repos/schematic/schematic/models/commands.py", line 121, in submit_manifest
    manifest_id = metadata_model.submit_metadata_manifest(
  File "/home/alamb/repos/schematic/schematic/models/metadata.py", line 349, in submit_metadata_manifest
    manifest_id = syn_store.associateMetadataWithFiles(
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 1178, in associateMetadataWithFiles
    manifest_synapse_table_id, manifest, table_manifest = self.uploadDB(
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 154, in wrapper
    return method(*args, **kwargs)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 791, in uploadDB
    manifest_table_id = self.buildDB(datasetId, table_name, col_schema, table_manifest, table_manipulation, restrict)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 868, in buildDB
    table_info = self.get_table_info(datasetId = datasetId)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 751, in get_table_info
    tables = self._get_tables(datasetId = datasetId, projectId = projectId)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 741, in _get_tables
    project = self.syn.get(self.getDatasetProject(datasetId))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 322, in iter
    return self.retry_error_callback(retry_state)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 1386, in raise_final_error
    return retry_state.outcome.result()
  File "/home/alamb/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/alamb/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/home/alamb/repos/schematic/schematic/store/synapse.py", line 1431, in getDatasetProject
    raise LookupError (
LookupError: The given dataset (syn51080454) doesn't appear in the configured file view (syn23643253). This might mean that the file view's scope needs to be updated.
```

**Comment by andrewelamb** [comment]
@milen-sage, @GiaJordan Never mind, it was an issue with my schematic config!
