### ISSUE TITLE
`AssertionError` when generating manifest for previously annotated "file-less" component

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#522]
## Describe the bug

I'm having trouble generating a Google Sheet manifest for a biospecimen dataset (_i.e._ without data files). I first encountered the issue in the Data Curator, and I was able to reproduce it with just schematic on my local machine. In the code block below, you can see that I'm able to create a manifest from a previously annotated `BulkRNAseqLevel1` dataset, but the same command for a previously annotated `Biospecimen` dataset fails with an `AssertionError` in `pygsheets`. 

I'm going to do some more digging, but I wanted to create a ticket to report any findings. 

I'm using the latest commit (b01bd03c1e9a3cd0b5c610c9af5aea2ecc119750) on the `develop` branch. This issue happened on both my local machine (macOS) and on the Shiny Server (Linux)

```
❯ schematic manifest --config ../imcore_data_model/config.yml get --data_type "BulkRNAseqLevel1" --jsonld ../imcore_data_model/imcore.model.jsonld --sheet_url --dataset_id syn26010235 
[...]
Permission Id: anyoneWithLink
Find the manifest template using this Google Sheet URL:
https://docs.google.com/spreadsheets/d/10YWjZy41Aktqh0KiipzTVrxUCXw5WS5cuEUVpbTs1Qc


❯ schematic manifest --config ../imcore_data_model/config.yml get --data_type "Biospecimen" --jsonld ../imcore_data_model/imcore.model.jsonld --sheet_url --dataset_id syn26011024 
[...]
Permission Id: anyoneWithLink
Traceback (most recent call last):
  File "/Users/bgrande/Repos/schematic-dev/.venv/bin/schematic", line 5, in <module>
    main()
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/bgrande/Repos/schematic-dev/schematic/manifest/commands.py", line 135, in get_manifest
    result = manifest_generator.get_manifest(
  File "/Users/bgrande/Repos/schematic-dev/schematic/manifest/generator.py", line 956, in get_manifest
    pop_manifest_url = self.populate_manifest_spreadsheet(
  File "/Users/bgrande/Repos/schematic-dev/schematic/manifest/generator.py", line 994, in populate_manifest_spreadsheet
    manifest_sh = self.set_dataframe_by_url(empty_manifest_url, manifest)
  File "/Users/bgrande/Repos/schematic-dev/schematic/manifest/generator.py", line 816, in set_dataframe_by_url
    wb.set_data_validation(start = start_col, end = end_col, condition_type = None)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/pygsheets/utils.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/pygsheets/worksheet.py", line 1624, in set_data_validation
    grange = GridRange(worksheet=self, start=start, end=end)
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/pygsheets/address.py", line 245, in __init__
    self._apply_index_constraints()
  File "/Users/bgrande/Repos/schematic-dev/.venv/lib/python3.9/site-packages/pygsheets/address.py", line 417, in _apply_index_constraints
    assert self._start[1] <= self._end[1]
AssertionError
```

## To Reproduce

TBD. I'll see if I can reproduce the issue with the example data model that we use for testing since it has a `Patient` component that's not a file-based data type. 

## Expected behavior

I'm expecting a Google Sheet template to be generated, which contains the entity IDs so that submission doesn't create a new set of uniquely named folders.

**Comment by milen-sage** [comment]
@BrunoGrandePhD this looks similar to https://github.com/Sage-Bionetworks/data_curator/issues/190

I'll be pushing a fix to develop in the next few hours.

**Comment by BrunoGrandePhD** [comment]
Ah, okay! I'll pause my investigations for now. Once your fix is pushed, I'll validate it on my end. If that fixes my issue, then I'll close this issue. Otherwise, I'll resume digging.
