### ISSUE TITLE
Invalid validation rule in example.model.jsonld

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic#689]
**Describe the bug**

When validating the Invalid_Test_Manifest.csv for the example MockComponent data type I get 

error: The json_schema, has an error in the validation rule for the attribute: CheckMatchatLeast, the provided validation rules (matchAtLeastOne MockComponent.checkMatchatLeast Patient.PatientID) is not a valid rule. Please check spelling.

Traceback:

Traceback (most recent call last):
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/bin/schematic", line 11, in <module>
    sys.exit(main())
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/models/commands.py", line 159, in validate_manifest
    inputMModelLocation=jsonld, inputMModelLocationType=model_file_type
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/models/metadata.py", line 60, in __init__
    self.sg = SchemaGenerator(inputMModelLocation)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/schemas/generator.py", line 65, in __init__
    self.se.load_schema(self.jsonld_path)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/schemas/explorer.py", line 52, in load_schema
    self.schema_nx = load_schema_into_networkx(self.schema)
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/utils/schema_utils.py", line 122, in load_schema_into_networkx
    input_filetype = 'json_schema')
  File "/Users/milen-sage/workspace/schematic-dev/schematic/venv-dev/lib/python3.7/site-packages/schematic/utils/validate_rules_utils.py", line 172, in validate_schema_rules
    f"The {input_filetype} has an error in the validation_rules set "
jsonschema.exceptions.ValidationError: The json_schema has an error in the validation_rules set for attribute CheckMatchatLeast. Validation failed with the following errors: [['NA', 'CheckMatchatLeast', 'The json_schema, has an error in the validation rule for the attribute: CheckMatchatLeast, the provided validation rules (matchAtLeastOne MockComponent.checkMatchatLeast Patient.PatientID) is not a valid rule. Please check spelling.', 'Not a Rule'], ['NA', 'CheckMatchatLeast', 'The json_schema, has an error in the validation rule for the attribute: CheckMatchatLeast, the provided validation rules (matchAtLeastOne MockComponent.checkMatchatLeast Patient.PatientID) is not a valid rule. Please check spelling.', 'Not a Rule']]

**To Reproduce**

Run 

`schematic model --config ./config.yml validate --manifest_path ./tests/data/mock_manifests/Invalid_Test_Manifest.csv --data_type MockComponent`

**Expected behavior**
I think the expected behavior is getting an error on the content of Invalid_Test_Manifest.csv.

**Priority** (select one)
- [v ] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - Mac OS X
 - on branch develop of schematic

**Additional context**
I was just playing around with the new validation rules. I haven't changed example.model.jsonld from upstream's develop branch.

**Comment by linglp** [comment]
A lot of my API calls are using `example.model.jsonld` as an input field. Fixing this bug could help some work on my end too!

**Comment by milen-sage** [comment]
Hmm, it sounds like this may be higher priority then. @GiaJordan do you think you could take a look this sprint?

**Comment by GiaJordan** [comment]
@linglp Could you create a separate issue for the behavior you observed?
@milen-sage and I just met and we were able to solve his, but we think that yours might have a different cause and a separate issue for it would be easier to track!

**Comment by milen-sage** [comment]
After a conversation with @GiaJordan I realized I messed up: I was trying to use new functionality w/o rebuilding the wheel containing it... Rebuilding resolved the issue!. Thanks @GiaJordan ! @linglp it sounds like you have a separate issue, and can follow up with @GiaJordan separately.

**Comment by linglp** [comment]
Thank you @GiaJordan and @milen-sage ! I created my bug here: https://github.com/Sage-Bionetworks/schematic/issues/696
