### ISSUE TITLE
Schema conversion fails "IndexError: string index out of range"

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/schematic#734]
**Describe the bug**
With the current develop branch, this schema (https://github.com/nf-osi/nf-metadata-dictionary/blob/97fc0254d736e02907971d07bda2405ab38c14f0/NF.csv) fails to build with `schematic schema convert`. With the `pip` version of schematic, it builds fine. 

**To Reproduce**
Using https://github.com/nf-osi/nf-metadata-dictionary/blob/97fc0254d736e02907971d07bda2405ab38c14f0/NF.csv, follow the steps in th code chunk below.

**Expected behavior**
I expected `schematic schema convert to work fine` 

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Additional context**

pip version: 
```
(data_curator_env) ➜  Downloads pip3 install schematicpy                  
Collecting schematicpy
....
Successfully installed schematicpy-1.0.0 synapseclient-2.3.1

(data_curator_env) ➜  Downloads schematic schema convert -v "DEBUG" NF.csv
Starting schematic...
Done adding requirements and value ranges to attributes
By default, the JSON-LD output will be stored alongside the first input CSV file. In this case, it will appear here: 'NF.jsonld'. You can use the `--output_jsonld` argument to specify another file path.
The Data Model was created and saved to 'NF.jsonld' location.

(data_curator_env) ➜  Downloads pip uninstall schematicpy                 
Found existing installation: schematicpy 1.0.0
Uninstalling schematicpy-1.0.0:
  Would remove:
    /opt/miniconda3/envs/data_curator_env/bin/schematic
    /opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/*
    /opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematicpy-1.0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled schematicpy-1.0.0
```

github develop version:
```
(data_curator_env) ➜  Downloads pip install git+https://github.com/Sage-Bionetworks/schematic@develop
Collecting git+https://github.com/Sage-Bionetworks/schematic@develop
...
Successfully installed schematicpy-1.0.0 synapseclient-2.5.1

(data_curator_env) ➜  Downloads schematic schema convert -v "DEBUG" NF.csv             
Starting schematic...
Traceback (most recent call last):
  File "/opt/miniconda3/envs/data_curator_env/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/schemas/commands.py", line 56, in convert
    base_se = _convert_csv_to_data_model(schema_csv, base_schema)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/schemas/df_parser.py", line 762, in _convert_csv_to_data_model
    base_se = create_nx_schema_objects(rfc_df, base_se)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/schemas/df_parser.py", line 420, in create_nx_schema_objects
    new_property = get_property(
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/schemas/df_parser.py", line 176, in get_property
    property_name = se.get_property_label_from_display_name(property_display_name)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/schematic/schemas/explorer.py", line 437, in get_property_label_from_display_name
    label = inflection.camelize(display_name.strip(), uppercase_first_letter=False)
  File "/opt/miniconda3/envs/data_curator_env/lib/python3.9/site-packages/inflection/__init__.py", line 168, in camelize
    return string[0].lower() + camelize(string)[1:]
IndexError: string index out of range
```

**Comment by mialy-defelice** [comment]
@allaway @milen-sage this looks like its an issue with a pandas update that only presents when there are no properties in the data model. I'll work on fixing it tomorrow.

**Comment by allaway** [comment]
Sounds good, thank you @mialy-defelice !

**Comment by mialy-defelice** [comment]
@ychae
