### ISSUE TITLE
Validation Rules in data model doesn't work

### ISSUE THREAD

**Issue by danlu1** [Sage-Bionetworks/schematic#752]
I tried to restrict the data type for attributes as numbers and put "num" in the data model csv. But after I generated the template, the validation rule doesn't apply. 

**Priority** (select one)
- [X] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**
data model:
<img width="857" alt="Screen Shot 2022-05-24 at 4 35 54 PM" src="https://user-images.githubusercontent.com/90745557/170152737-27af57a8-1105-403e-8121-e1e1e84ee12a.png">

template: 
<img width="1321" alt="Screen Shot 2022-05-24 at 5 20 48 PM" src="https://user-images.githubusercontent.com/90745557/170152706-1187066e-ad7f-4cc4-b2bf-9f6cef44d99c.png">

**Comment by milen-sage** [comment]
AC: reproduce bug, diagnose and fix.

**Comment by GiaJordan** [comment]
@danlu1 Can you post or link to the data model and template you experienced this on please?

**Comment by danlu1** [comment]
@GiaJordan here attached the data model and link to the template.
Data model: [1kD.demographic.data.model.csv](https://github.com/Sage-Bionetworks/schematic/files/8864028/1kD.demographic.data.model.csv)
Template: https://docs.google.com/spreadsheets/d/19PD4mNCylBUAz6x7n0Wpj22I1OuFv8NcwPstCm5XzEw/edit#gid=0

**Comment by GiaJordan** [comment]
Thanks @danlu1!
What does your output look like when you run `schematic model validate` on the manifest?

**Comment by danlu1** [comment]
I ran `schematic model --config config.yml validate -mp ./1kD.demographic.data.model.csv -dt 1kDStandardizedDemographicData` and got this error: 
```
(.venv) ec2-user@ip-10-41-28-89 ~/sysbioDCCjsonschemas/schematic_schemas/code -  (1kD_individual_temmplate) $ schematic model --config config.yml validate -mp ./1kD.demographic.data.model.csv -dt 1kDStandardizedDemographicData
Starting schematic...
The (model > input > location) argument with value './minimal.model.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
Traceback (most recent call last):
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/schematic/models/commands.py", line 147, in validate_manifest
    manifestPath=manifest_path, rootNode=data_type, jsonSchema=json_schema
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/schematic/models/metadata.py", line 209, in validateModelManifest
    rootNode, rootNode + "_validation"
  File "/home/ec2-user/sysbioDCCjsonschemas/schematic_schemas/code/.venv/lib64/python3.7/site-packages/schematic/schemas/generator.py", line 481, in get_json_schema_requirements
    raise ValueError(f"'{source_node}' is not a valid component in the schema.")
ValueError: '1kDStandardizedDemographicData' is not a valid component in the schema.
```

**Comment by GiaJordan** [comment]
@milen-sage @ychae 

Currently unable to reproduce, validating a similar manifest with the provided data model on the latest version of `develop` produced the output:
```
Starting schematic...
The (model > input > location) argument with value 'tests/data/1kD.demographic.data.model.jsonld' is being read from the config file.
The (model > input > file_type) argument with value 'local' is being read from the config file.
JSON schema successfully generated from schema.org schema!
JSON schema file log stored as tests/data/1kD.demographic.data.1kDStandardizedDemographicData.schema.json
C:\Users\gjordan\anaconda3\envs\schematic\lib\site-packages\jinja2\environment.py:1088: DeprecationWarning: 'soft_unicode' has been renamed to 'soft_str'. The old name will be removed in MarkupSafe 2.1.
  return concat(self.root_render_func(self.new_context(vars)))
        2 expectation(s) included in expectation_suite.
Calculating Metrics: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 100.90it/s]/s]
error: On row 3 the attribute noOfChildren does not contain the proper value type num.
error: On row 2 the attribute noOfAdults does not contain the proper value type num.                                                                                                                                                                                                                     '']
[[3, 'noOfChildren', 'On row 3 the attribute noOfChildren does not contain the proper value type num.', 'd'], [2, 'noOfAdults', 'On row 2 the attribute noOfAdults does not contain the proper value type num.', 'd'], [2, 'householdID', "'' is too short", ''], [2, 'individualID', "'' is too short",ngua ''], [2, 'sex', "'' is not one of ['female', 'unknown', 'mixed sex', 'male']", ''], [2, 'spokenLanguage', "'' is not one of ['Sino-Tibetan Language', 'Austroasiatic Language', 'Romance Language', 'Sandawe Language', 'Aragonese Language', 'Tsimshian Language', 'Eastern Romance Language', 'Walloomansn Language', 'Friulian Language', 'North American Indian Language', 'Italian Language', 'Georgian Language', 'Spanish Language', 'Uralic Language', 'US Spanish', 'Haida Language', 'Nilotic Language', 'Kanuri Language', 'Arawakan Language', 'Manchu Language', 'Papiamento Language', 'Turkic Langua'' ige', 'Romansh La", ''], [2, 'program', "'' is not one of ['1kD']", ''], [2, 'project', "'' is not one of ['DyadicSociometrics', 'M4EFaD', 'Connectome', 'CompNeuroDev', 'MicrobiomeBrainDevelopment', 'Assembloids', 'InfantNaturalStatistics', 'First1000Daysdatabase', 'BRAINRISE', 'KHULA']", ''], [2]", , 'study', "'' is not one of ['M4EFaD_MAMSintervention', 'DyadicSociometrics', 'KHULA_CapeTown', 'Connectome', 'CompNeuroDev', 'MicrobiomeBrainDevelopment', 'KHULA_Blantyre', 'M4EFaD_MAMS', 'Assembloids', 'M4EFaD_BEST', 'M4EFaD_BMT', 'First1000Daysdatabase', 'InfantNaturalStatistics', 'BRAINRISEof [', 'M4EFaD_LABS']", ''], [2, 'person', "'' is not one of ['father', 'child', 'other caregiver', 'mother']", ''], [3, 'householdID', "'' is too short", ''], [3, 'individualID', "'' is too short", ''], [3, 'sex', "'' is not one of ['female', 'unknown', 'mixed sex', 'male']", ''], [3, 'spokenLangua', 'ge', "'' is not one of ['Sino-Tibetan Language', 'Austroasiatic Language', 'Romance Language', 'Sandawe Language', 'Aragonese Language', 'Tsimshian Language', 'Eastern Romance Language', 'Walloon Language', 'Friulian Language', 'North American Indian Language', 'Italian Language', 'Georgian Lang4EFauage', 'Spanish Language', 'Uralic Language', 'US Spanish', 'Haida Language', 'Nilotic Language', 'Kanuri Language', 'Arawakan Language', 'Manchu Language', 'Papiamento Language', 'Turkic Language', 'Romansh La", ''], [3, 'program', "'' is not one of ['1kD']", ''], [3, 'project', "'' is not one iome
of ['DyadicSociometrics', 'M4EFaD', 'Connectome', 'CompNeuroDev', 'MicrobiomeBrainDevelopment', 'Assembloids', 'InfantNaturalStatistics', 'First1000Daysdatabase', 'BRAINRISE', 'KHULA']", ''], [3, 'study', "'' is not one of ['M4EFaD_MAMSintervention', 'DyadicSociometrics', 'KHULA_CapeTown', 'Connectome', 'CompNeuroDev', 'MicrobiomeBrainDevelopment', 'KHULA_Blantyre', 'M4EFaD_MAMS', 'Assembloids', 'M4EFaD_BEST', 'M4EFaD_BMT', 'First1000Daysdatabase', 'InfantNaturalStatistics', 'BRAINRISE', 'M4EFaD_LABS']", ''], [3, 'person', "'' is not one of ['father', 'child', 'other caregiver', 'mother']", '']]
```

Valid value errors are expected the rest of the manifest, besides `noOfChildren` and `noOfAdults`, were left empty. The validation suite is catching the strings entered instead of numerical data.

Will follow up with @danlu1 to try and solve

**Comment by GiaJordan** [comment]
Manifest validation is performing as expected when run. Validation during metadata entry within Google Sheets is not supported, aside from checks against specified `valid values` and the `regex match` validation rule
