### ISSUE TITLE
Issue with intermediate JSON schema file storage

### ISSUE THREAD

**Issue by PozhidayevaDarya** [Sage-Bionetworks/schematic#865]
**Describe the bug**
The issue occurs when generating a google sheet template which points schematic to a json-ld model. 
This may be related to improper intermediate JSON schema file storage as the error dead-ends in FileNotFoundError: [Errno 2] No such file or directory.' More detail is shown below.

**To Reproduce**
1. Follow the installation guide [here](https://github.com/Sage-Bionetworks/schematic#installation-guide-for-developerscontributors).
2. export the HTAN model google sheet to csv
3. run [this schematic command](https://sage-schematic.readthedocs.io/en/develop/cli_reference.html#schematic-schema-convert) to generate a json-ld file from the csv
4. run [this schematic command](https://sage-schematic.readthedocs.io/en/develop/cli_reference.html#schematic-manifest-get) to generate a manifest: e.g. schematic manifest -c config-htan.yml get -t BiospecimenTest -dt Biospecimen --jsonld 'HTAN schema.jsonld' -s -oa 
5.  See error

`(synapse_env) (base) darya@tigerlily synapse_env % schematic manifest -c load_metadata/config-htan.yml get -t BiospecimenTest -dt Biospecimen --jsonld 'HTAN schema v22.02 - latest.jsonld' -s -oa  
Starting schematic...
URL being requested: POST https://www.googleapis.com/drive/v3/files/1LYS5qE4nV9jzcYw5sXwCza25slDfRA1CIg3cs-hCdpU/copy?alt=json
JSON schema successfully generated from schema.org schema!
Traceback (most recent call last):
  File "/Users/darya/Documents/synapse_env/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/manifest/commands.py", line 189, in get_manifest
    result = create_single_manifest(data_type = dt, output_csv=output_csv, output_xlsx=output_xlsx)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/manifest/commands.py", line 148, in create_single_manifest
    result = manifest_generator.get_manifest(
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/manifest/generator.py", line 1442, in get_manifest
    return self.get_empty_manifest(json_schema_filepath=json_schema)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/manifest/generator.py", line 1247, in get_empty_manifest
    json_schema = self._get_json_schema(json_schema_filepath)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/manifest/generator.py", line 346, in _get_json_schema
    json_schema = self.sg.get_json_schema_requirements(self.root, self.title)
  File "/Users/darya/Documents/synapse_env/lib/python3.9/site-packages/schematic/schemas/generator.py", line 711, in get_json_schema_requirements
    os.makedirs(os.path.dirname(json_schema_log_file), exist_ok=True)
  File "/Users/darya/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''`

**Desktop (if applicable, please complete the following information):**
 - OS: MacOS

**Additional context**
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/zsh
TERM=xterm-256color
TMPDIR=/var/folders/db/2y351vcd2tq30k3nd44srrlm0000gp/T/
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=25E6CB91-F27E-49B4-8D53-E49E1DB068D5
USER=darya
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.H1OojV5CWd/Listeners
PATH=/Users/darya/Documents/synapse_env/bin:/Users/darya/opt/miniconda3/bin:/Users/darya/opt/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
LaunchInstanceID=C550B651-F00E-4FB8-8C17-4ADAD257352D
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/darya/Documents/synapse_env
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/darya
LOGNAME=darya
SECURITYSESSIONID=18702
OLDPWD=/Users/darya/Documents/synapse_env/load_metadata
CONDA_EXE=/Users/darya/opt/miniconda3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/darya/opt/miniconda3/bin/python
CONDA_SHLVL=1
CONDA_PREFIX=/Users/darya/opt/miniconda3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base) 
VIRTUAL_ENV=/Users/darya/Documents/synapse_env
PS1=(synapse_env) (base) %n@%m %1~ %# 
LANG=en_US.UTF-8
_=/usr/bin/env

**Comment by milen-sage** [comment]
@GiaJordan if you have time during this sprint extension could you take a look at what may be causing this error (if not we can prioritize for next sprint)? It may be a misconfiguration in the default config we use in schematic's installation; but it could be something different.

**Comment by GiaJordan** [comment]
@PozhidayevaDarya can you link to the HTAN Model you experienced this with please?

**Comment by GiaJordan** [comment]
> @PozhidayevaDarya ~~can you link to the HTAN Model you experienced this with please?~~

Nevermind, I was able to reproduce with example data model

**Comment by milen-sage** [comment]
Looks like this has been marked as done 🚀 ,  @GiaJordan I'm curious what was the cause for the error?

**Comment by GiaJordan** [comment]
> Issue 865 arose when a .jsonld file was used from the users current directory. A safeguard in place created the directory specified in the path to the .jsonld, but when it was in the current directory and the path was simply the name of the file, this field was `''`. 

@milen-sage

**Comment by PozhidayevaDarya** [comment]
Hey Gianna,

Sure here it is:
https://github.com/ncihtan/data-models/blob/main/HTAN.model.csv

Thanks,
Dar'ya
