### ISSUE TITLE
Submitting a manifest as a table 

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#954]
**Describe the bug**
The submit endpoint in API and also CLI didn't work. For CLI
try the following command of submitting a manifest: `schematic model -c config.yml submit -mp /Users/lpeng/Downloads/Patient-Metadata-Manifest.csv -d syn23643250 -vc Patient -mrt table`

The error message seems to be related to project scope. 

See errors below: 

```
Traceback (most recent call last):
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/bin/schematic", line 6, in <module>
    sys.exit(main())
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/models/commands.py", line 115, in submit_manifest
    manifest_id = metadata_model.submit_metadata_manifest(
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/models/metadata.py", line 347, in submit_metadata_manifest
    manifest_id = syn_store.associateMetadataWithFiles(
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/store/synapse.py", line 1075, in associateMetadataWithFiles
    manifest_synapse_table_id, manifest, table_manifest = self.upload_format_manifest_table(
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/store/synapse.py", line 138, in wrapper
    return method(*args, **kwargs)
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/store/synapse.py", line 739, in upload_format_manifest_table
    table_info = self.get_table_info()
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/store/synapse.py", line 730, in get_table_info
    tables = self._get_tables()
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/store/synapse.py", line 722, in _get_tables
    project = self.syn.get(self.project_scope[0])
    
   TypeError: 'NoneType' object is not subscriptable
```
**Expected behavior**

**Priority** (select one)
- [ ] Minor ⬇️
- [X] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by milen-sage** [comment]
@linglp at this time the submit CLI and respective API call, requires project scope when using the `mrt` option.

@GiaJordan is aware that project scope is not necessary for the CLI in general, so this will be adjusted going forward. Let's keep this ticket open and keep track of the work.

This reminds me, I need to check in on rebuilding the RDT, so that we can update the CLI reference.

**Comment by linglp** [comment]
Okay. Thank you @milen-sage ! I will create an issue for myself to add `project_scope` as a separate parameter on swagger UI and a separate issue for documentation

**Comment by GiaJordan** [comment]
@milen-sage @linglp after more digging, including the current project in some form may be necessary for facilitate the table replace behavior just implemented. Currently, all the tables for a given project are searched to decide whether to replace or create a new table when uploading a manifest. I'll investigate further, this is just preliminary findings
